<p>There are two types of DC motors in common use: brushed DC motor, and brushless DC motor (or BLDC motor). The name brushless DC motor is relative to the brushed DC motor. Brushed DC motor consists of stator, rotor, brushes and commutator, the function of brushes and commutator is to switch direction. Brushless DC motor is composed of stator and rotor, without brushes and commutator compared to the brushed DC motor. In many applications, either brushed or brushless DC motors can be used. However, both of the two types of motors have their own characteristics. The choice of which type of motor is determined by the specific application requirements.</p>
<h3><b>Difference in working principle</b></h3>
<p>Brushless DC motor: Brushless DC motors replace the mechanical commutation function with electronic commutation. The rotor of the motor is attached with magnetized permanent magnets, and in order to detect the polarity of the motor rotor, a position sensor is installed in the motor. According to the position signal from the position sensor, the motor controller switches the direction of the current in the coil winding to ensure that the magnetic force in the correct direction is generated to drive the motor. </p>
<p>Brushed DC motor: When the motor rotates, the carbon brushes slide on the commutator to produce a rotating magnetic field that is attracted to the static magnetic field of the stator. The current in the armature and stator windings is supplied by a battery or other DC power supply.</p>
<div>
<div style="width: 50%; float:left">
<img src="https://www.omc-stepperonline.com/image/catalog/blog/BLDC%20motor.png" style="width:70%">
<h6 style="margin-left:25%">BLDC motor</h6>
</div>
<div style="width: 50%; float:left">
<img src="https://www.omc-stepperonline.com/image/catalog/blog/BDC%20motor.png" style="width:70%">
<h6 style="margin-left:30%">BDC motor</h6>
</div>
<div style="clear:both"></div>
</div>
<h3><b>Difference of speed control method</b></h3>
<p>In fact, the speed control of brushless DC and brush DC motors mainly rely on voltage to control. The difference between the two is that brushless DC motor uses electronic commutation, which means that it has to have digital control to achieve commutation. Brushed DC motor is through the carbon brushes to commutate, and can be controlled by using traditional analog circuits such as thyristor, which is relatively simple. </p>
<p>The speed control process of brushed DC motor is to adjust the voltage level of the power supply of the motor. The adjusted voltage and current are converted through the rectifier and brushes, thus changing the strength of the magnetic field generated by the electrodes , which will eventually change the speed. This process is to change the voltage to regulate the speed.</p>
<p>In the speed control process of brushless DC motor, the supply voltage of the motor remains unchanged, by changing the control signal of the ESC, and then changing the switching rate of the high-power MOS tube through the microprocessor to realize the speed change. This process is to change the frequency to regulate the speed.</p>
<h3><b>Differences in performance</b></h3>
<p><b>Low noise and smooth operation of BLDC motors</b></p>
<p>Without brushes, brushless DC motors operate with much less friction, which makes them run smoothly and with much lower noise, and this benefit is a great support for model running stability. Therefore, it is suitable to be used in some places that need to be quiet such as hospitals, banks, airports, schools, etc.</p>
<p><b>Less interference of BLDC motors</b></p>
<p>By removing the brush, the most direct change is that the brushless DC motors do not have the electric sparks generated by the brushed DC motor operation, which greatly reduces the interference of electric sparks to the radio remote control equipment. It can be used in some flammable and explosive places.</p>
<p><b>Long life and no frequent maintenance of BLDC motors</b></p>
<p>The life of carbon brushes has a certain limit, for example, the carbon brushes will be worn out in a thousand hours, so brushed DC motors need to replace the brushes frequently. Brushless DC motors do not have brushes, the wear and tear of brushless motors is mainly on the bearings. The brushless DC motor is almost a kind of maintenance-free motor in mechanical terms, and it only needs some dust removal maintenance if necessary.</p>
<p><b>Easy speed control of BLDC motors</b></p>
<p>Brushless DC motors are usually digital frequency control with strong controllability, speed regulation from a few revolutions per minute to tens of thousands of revolutions per minute can be easily achieved. Brushed DC motors generally work at a constant speed after starting, and their speed regulation is not very easy. Series excitation motor can also reach 20,000 rpm, but the working life will be relatively short.</p>
<p><b>Simple structure , low cost and easy maintenance of brushed DC motors</b></p>
<p>The mechanism of brushed DC motor is simple and easy to control as it can work without control circuit. It is easy to produce and process, so the cost is low. If the brushed DC motor fails, it only needs to replace the carbon brushes, which is easy to repair. Brushless DC motor has permanent magnets on the rotor, and it needs the control of circuit for its operation, so the cost is high. Brushless DC motors can only be replaced if they are damaged.</p>
<p><b>Fast starting response and high starting torque of brushed DC motors</b></p>
<p>Brushed DC motors have fast starting response, high starting torque, smooth variable speed, almost no vibration felt from zero to maximum speed, and can drive a larger load when starting. Brushless DC motors have large starting resistance (inductive resistance), so the power factor is small, the starting torque is relatively small, there is a humming sound and strong vibration when starting, and the load driven when starting is smaller.</p>
<p><b>Smooth operation and excellent starting and braking of brushed DC motors</b></p>
<p>The speed regulation of brushed DC motors is through voltage regulation, so they run smoothly in starting and braking, and also smoothly in constant speed operation. Firstly, AC becomes DC, then DC becomes AC, and the speed is controlled by frequency change, so brushless DC motors run unsteadily and vibrate a lot when starting and braking, and only run smoothly when the speed is constant.</p>
<p><b>High control accuracy of brushed DC motors</b></p>
<p>Brushed DC motors are usually used together with gearboxes and encoders to give the motors greater output power and higher control accuracy. The control accuracy can reach 0.01mm, which allows the moving parts to stop almost anywhere you want. All precision machine tools use DC motors for control accuracy. However, Brushless DC motors are not smooth in starting and braking, so the moving parts stop at different positions each time and must be stopped at the desired position by positioning pins or limiters. </p>
<p><b>Energy-saving and environment-friendly of brushless DC motors</b></p>
<p>Relatively speaking, brushless DC motors controlled with frequency conversion will be more energy-efficient than series-excited motors, the most typical examples being inverter air conditioners and refrigerators.</p>
<h3><b>Summary of differences</b></h3>
<table border="1" style="border-color:1px solid #333;border-collapse: collapse;width:80%;text-align:center">
	<tbody><tr>
		<td style="padding:8px"><b>Differences</b></td>
		<td style="padding:8px"><b>Brushless DC motor
		</b></td><td style="padding:8px"><b>Brushed DC motor</b></td>
	</tr>
	<tr>
		<td style="padding:8px">Structure</td>
		<td style="padding:8px">Complex</td>
	    <td style="padding:8px"><font color="#0000ff">Simple</font></td>
	</tr>
	<tr>
		<td style="padding:8px">Maintenance </td>
		<td style="padding:8px">Can only replace the motor</td>
	    <td style="padding:8px"><font color="#0000ff">Easy, just replace the brushes</font></td>
	</tr>
	<tr>
		<td style="padding:8px">Cost </td>
		<td style="padding:8px">Higher (plus brushless ESC)</td>
		<td style="padding:8px"><font color="#0000ff">Low </font></td>
	</tr>
		<tr>
		<td style="padding:8px">Control</td>
		<td style="padding:8px">More complex</td>
		<td style="padding:8px"><font color="#0000ff">Easy</font></td>
	</tr>	
		<tr>
		<td style="padding:8px">Response time</td>
		<td style="padding:8px">Slow</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Fast</font></td>
	</tr>	
		<tr>
		<td style="padding:8px">Starting torque </td>
		<td style="padding:8px">Relatively small</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Large (low speed)</font></td>
	</tr>	
		<tr>
		<td style="padding:8px">Speed change</td>
		<td style="padding:8px">Vibration</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Smoothing</font></td>
	</tr>	
		<tr>
		<td style="padding:8px">Start-brake effect</td>
		<td style="padding:8px">Not smooth, high vibration</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Smooth, good effect</font></td>
	</tr>	
		<tr>
		<td style="padding:8px">Control accuracy</td>
		<td style="padding:8px">By means of positioning pins or limiters</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">High accuracy 0.01mm</font></td>
	</tr>	
		<tr>
		<td style="padding:8px">Speed control</td>
		<td style="padding:8px"><font color="#0000ff">Can be adjusted by frequency conversion, easy</font></td>
		<td style="padding:8px"><font style="">adjust voltage to regulate speed, not easy</font></td>
	</tr>	
		<tr>
		<td style="padding:8px">Commutation</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Electronic commutation</font></td>
		<td style="padding:8px">Mechanical commutation</td>
	</tr>	
		<tr>
		<td style="padding:8px">Torque per unit mass </td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Large</font></td>
		<td style="padding:8px">Small</td>
	</tr>	
	<tr>
		<td style="padding:8px">Torque per unit power </td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Large</font></td>
		<td style="padding:8px">Small</td>
	</tr>	
		<tr>
		<td style="padding:8px">Reliability</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">High</font></td>
		<td style="padding:8px">Low</td>
	</tr>	
		
		<tr>
		<td style="padding:8px">Heat dissipation</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Fast</font></td>
		<td style="padding:8px">Slow</td>
	</tr>	
		
		<tr>https://github.com/MarkBeren/Brushless-DC-Motor/tree/main
		<td style="padding:8px">Interference</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Low, no spark</font></td>
		<td style="padding:8px">High, with electric spark</td>
	</tr>	
		
		<tr>
		<td style="padding:8px">Noise</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Small</font></td>
		<td style="padding:8px">Large</td>
	</tr>	
		
		<tr>
		<td style="padding:8px">Working life</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Long</font></td>
		<td style="padding:8px">Short</td>
	</tr>	
		
		<tr>
		<td style="padding:8px">Energy consumption</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Lower</font></td>
		<td style="padding:8px">Higher</td>
	</tr>	
		
		<tr>
		<td style="padding:8px">Fault rate</td>
		<td style="padding:8px"><font color="#0000ff" style="background-color: rgb(255, 255, 255);">Low</font></td>
		<td style="padding:8px">High</td>
	</tr>	
		
		<tr>
		<td style="padding:8px">Applications</td>
		<td style="padding:8px">Constant speed equipment, air conditioners, refrigerators, drones, dust-free, explosion-proof, food, etc.</td>
		<td style="padding:8px">Precision instruments, printers, etc.</td>
	</tr>	
</tbody></table>
